spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/query-dsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true # console창에 sql 실행 로그 확인 가능.

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

